Extend support for Snowflake
snowplow/composable-cdp-with-predictive-ml-modeling-accelerator pull request #17
Opened 2023-03-10 12:27 UTC by georgewoodhead

## Description & motivation
Extend accelerator support for Snowflake. This includes:
- Creating new Jupyter notebooks to train and deploy the propensity to convert machine learning models with Snowpark for python
- Add instructions to connect Snowflake with Hightouch
- Make content more generic to work with both Snowflake and Databricks

Other improvements:
- Mention Fractional Attribution DPA in the next steps
- Add mention of how to benchmark the modelling

## Checklist
- [x] I have updated the README.md (if applicable)

2023-03-13 15:00 UTC, rlh1994 requested changes
Couple of things as I was working through, but otherwise looks good and clean!

- Can we make clear which schema their sessions should be connecting to (i.e. the one that has what tables, is it my main schema or my derived one?)
- It might be worth adding in as to why we would want to create this function to train our model given we just did it (i.e. because we should regularly re-train our model to avoid model drag, and this makes it easier to do so).
- Maybe in the configuration in later notebooks, unless there is any difference, just call out they only need to do this if they have not done it before/their setup has chagned from the previous steps?
- Can we add the final image to the introduction under what you will build as well as the dashboard image? I think it's great to show the things that you'll have by the end outside just the dashboard given how much of it is the model.
- As discussed on slack, if we can split the steps for databricks/snowflake under different sub-headers on the nav menu that would be ideal, one for @Jack-Keene ?

Other than that looks good!

2023-03-14 09:28 UTC, Jack-Keene commented
By next level of header do you mean something like:

1. Predictive ML Modeling
   - Databricks
         - Model Training
         - Using Your Model
   - Snowflake
         - Model Training
         - Using Your Model

2023-03-14 09:28 UTC, rlh1994 commented
@Jack-Keene Yep

2023-03-14 12:34 UTC, Jack-Keene commented
This should be pretty straightforward to do, I think all you need to do is add a 'databricks' and 'snowflake' folder to add subheaders. Happy to jump on a call if that doesnt work

2023-03-14 16:57 UTC, Jack-Keene commented on config.toml
>    author = "Snowplow, George Woodhead"
Can we add a parameter to disable intercom here: 
`intercom=false`

2023-03-15 11:09 UTC, merged